# Generated by Django 5.0.1 on 2024-04-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_alter_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
