# Generated by Django 5.0.1 on 2024-07-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0011_billinginformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='verified_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
