# Generated by Django 5.0.1 on 2024-05-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0003_product_category_alter_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
            ],
        ),
        
        migrations.RemoveField(
            model_name='product',
            name='sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='MAIN.sizeavailable'),
        ),
    ]
