# Generated by Django 5.0.1 on 2024-05-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0004_sizeavailable_product_category_remove_product_sizes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='size_available',
        ),
        
    ]
