# Generated by Django 5.0.1 on 2024-05-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0005_rename_size_product_size_available_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(default=None, blank=True,null=True, upload_to='product_images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(default=None,blank=True,null=True, upload_to='product_images/'),
        ),
    ]
