# Generated by Django 5.0.1 on 2024-05-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0006_product_category_product_image_2_product_image_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(to='MAIN.productcategory'),
        ),
    ]
