# Generated by Django 5.0.1 on 2024-04-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0007_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
