# Generated by Django 5.0.1 on 2024-07-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN', '0007_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizeavailable',
            options={'ordering': ['size']},
        ),
        migrations.AddField(
            model_name='shoebrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='brand_images/'),
        ),
    ]
